
export const metadata = {
    title: 'Youtube Repository',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <div>
            {children}
        </div>
    )
}
